# Generated by Django 3.2.5 on 2022-11-23 01:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.AddField(
            model_name='item',
            name='imageURL',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
