# Generated by Django 4.1 on 2022-11-23 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_listing_creatby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='creatby',
            new_name='createby',
        ),
    ]
