# Generated by Django 4.1 on 2022-11-23 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_rename_creatby_listing_createby'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bid',
            name='listing_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='auctions.listing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bid',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_bid', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='createby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_listing', to=settings.AUTH_USER_MODEL),
        ),
    ]
