# Generated by Django 4.1 on 2022-11-23 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_bid_bid_bid_listing_id_bid_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='listing_id',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='user_id',
            new_name='user',
        ),
    ]
