# Generated by Django 4.1 on 2022-11-23 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_rename_listing_id_bid_listing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='listing',
            new_name='listing_id',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='user',
            new_name='user_id',
        ),
    ]
